### ISSUE TITLE
set_mongodb_password.sh never completes if db is locked

### ISSUE THREAD

**Issue by anton-107** [tutumcloud/tutum-docker-mongodb#11]
The removing of the lock should occur before calling /set_mongodb_password.sh

Otherwise, if the db is locked on container restart you will keep getting "Waiting for confirmation of MongoDB service startup" without proceeding further

**Comment by tifayuki** [comment]
Hi @anton-107 
Can you create a PR, so that I can merge it :)

Thank you

**Comment by anton-107** [comment]
@tifayuki here:
https://github.com/tutumcloud/tutum-docker-mongodb/pull/12
